version: '3.8'

services:
  app:
    build: .
    container_name: fusion-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - DATABASE_URL=postgresql://fusion:fusion123!!@localhost:5432/fusion?client_encoding=utf8
      - DEFAULT_MODEL=${DEFAULT_MODEL:-}
      - SEARCH_API_KEY=${SEARCH_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - ANTHROPIC_API_BASE=${ANTHROPIC_API_BASE:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GOOGLE_API_BASE=${GOOGLE_API_BASE:-}
      - HUNYUAN_APP_ID=${HUNYUAN_APP_ID:-}
      - HUNYUAN_SECRET_ID=${HUNYUAN_SECRET_ID:-}
      - HUNYUAN_SECRET_KEY=${HUNYUAN_SECRET_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY:-}
      - VOLCENGINE_API_KEY=${VOLCENGINE_API_KEY:-}
      - VOLCENGINE_API_BASE=${VOLCENGINE_API_BASE:-}
      - QIANFAN_AK=${QIANFAN_AK:-}
      - QIANFAN_SK=${QIANFAN_SK:-}
      - XAI_API_KEY=${XAI_API_KEY:-}
      - XAI_API_BASE=${XAI_API_BASE:-}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M