version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: fusion-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - fusion_fusion_network

networks:
  fusion_fusion_network:
    external: true